-- DropForeignKey
ALTER TABLE "TEC_PARAMETROBASEPLICACAO" DROP CONSTRAINT "TEC_PARAMETROBASEPLICACAO_TEC_BaseAplicacaoId_fkey";

-- DropForeignKey
ALTER TABLE "TEC_PARAMETROBASEPLICACAO" DROP CONSTRAINT "TEC_PARAMETROBASEPLICACAO_TEC_ParametroCodigoCliente_fkey";

-- AddForeignKey
ALTER TABLE "TEC_PARAMETROBASEPLICACAO" ADD CONSTRAINT "TEC_PARAMETROBASEPLICACAO_TEC_ParametroCodigoCliente_fkey" FOREIGN KEY ("TEC_ParametroCodigoCliente") REFERENCES "TEC_PARAMETRO"("TEC_ParametroCodigoCliente") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TEC_PARAMETROBASEPLICACAO" ADD CONSTRAINT "TEC_PARAMETROBASEPLICACAO_TEC_BaseAplicacaoId_fkey" FOREIGN KEY ("TEC_BaseAplicacaoId") REFERENCES "TEC_BASEAPLICACAO"("TEC_BaseAplicacaoId") ON DELETE CASCADE ON UPDATE CASCADE;
